version: '3.8'

services:
  php:
    build: .
    container_name: simple_blog_php
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: simple_blog_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: simple_blog
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./sql:/docker-entrypoint-initdb.d   # Correct the file path here

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass

volumes:
  db_data: